# SPDX-License-Identifier: MIT

# CI that builds this vscode extension

name: build

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: |
          npm install --loglevel verbose
          npm install @vscode/vsce -g

      - name: compile
        run: npm run compile

      - name: remove dev dependencies
        run: npm prune --production

      - name: vsce package
        run: vsce package
