# SPDX-License-Identifier: MIT

# CI that builds this vscode extension

name: build

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - name: Install dependencies
        run: |
          npm install --loglevel verbose
          npm install @vscode/vsce typescript -g

      - name: Install ninja (Windows / Linux)
        if: runner.os != 'macOS'
        uses: turtlesec-no/get-ninja@main

      - name: Install ninja (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja

      - name: Make sure MSVC is found when Ninja generator is in use
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt 6.5.0
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.0
          cache: true

      - name: Build Qt test fixtures
        run: |
          cmake -S test/qt_test --preset=dev
          cmake --build test/qt_test/build-dev --verbose

      - name: compile
        run: npm run compile

      - name: test (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a npm test

      - name: test (non-Linux)
        if: runner.os != 'Linux'
        run: npm test

      - name: vsce package
        run: vsce package

      - name: Upload CMake and Build logs
        if: always() # Captures logs on success, failure, or cancellation
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: |
            test/qt_test/build-dev/CMakeFiles/CMakeOutput.log
            test/qt_test/build-dev/CMakeFiles/CMakeError.log
            test/qt_test/build-dev/CMakeCache.txt
            test/qt_test/build-dev/Testing/Temporary/**/*
