# SPDX-License-Identifier: MIT
# Creates the package

name: Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: |
          npm install --loglevel verbose
          npm install @vscode/vsce typescript -g
      - name: Package
        run: |
          npm install && npm run compile && npm prune --production && vsce package

      - name: Upload asset
        run: |
          sh upload_package.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
