on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Version Bump PR

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup git author name
        uses: fregante/setup-git-user@v2

      - name: Create PR to bump version
        run: |
          release-please release-pr --token=${{ secrets.GITHUB_TOKEN }} --repo-url=KDAB/vscode-qttest
